name: "Gitlab Python Publish Action"
description: Github action to build and publish Python packages to Gitlab
inputs:
  gitlab-token-user:
    description: User for the Gitlab token
    required: true
  gitlab-token:
    description: Gitlab Token
    required: true
  working-directory:
    description: An optional working directory to cd into before building
    required: false
    default: .

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - uses: actions/checkout@v2
    - name: Publish
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        export POETRY_VERSION=1.1.13 PATH=$HOME/.poetry/bin:$PATH
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
        poetry config repositories.source-python-packages https://gitlab.com/api/v4/projects/26335502/packages/pypi
        poetry config http-basic.source-python-packages ${{ inputs.gitlab-token-user }} ${{ inputs.gitlab-token }}
        poetry build
        poetry publish -r source-python-packages
